#!/home/andy/.nvm/versions/node/v14.15.5/bin/node

let fs = require("fs");
let Phrase = require("andyh-palindrome");

let text = fs.readFileSync("phrases.txt", "utf-8");
text.split("\n").forEach(function(line) {
  let phrase = new Phrase(line);

  if(phrase.palindrome()) {
    console.log("palindrome detected:", line);
    fs.writeFileSync("palindromes.txt", line + "\n", { flag: "a" });
  }
});
